language: node_js

node_js:
  - "6.9.5"

# addons:
#   postgresql: "9.5"



before_install:
  - pip install --user codecov





before_script:
  - "psql -c 'create database app_test;' -U postgres"
  - "psql -U postgres -d app_test -a -f database-build/db-build.sql"

script:
  - "npm run coverage"

after_success:
  - codecov --file coverage/lcov.info --disable search
  - bash <(curl -s https://codecov.io/bash)
